### ISSUE TITLE
No module named `dynamic_validator.field_validation` 

### ISSUE THREAD

**Issue by upMKuhn** [jackton1/django-dynamic-model-validation#7]
Hi, 
I can't install it propperly using pipenv. I checked the folder and there are only 2 files. apps and tests. The former doesn't contain any code?

```
from django.apps import AppConfig
class DynamicValidatorConfig(AppConfig):
    name = 'dynamic_validator'

```

> File "~/.local/share/virtualenvs/project-kb6U_ucp/lib/python3.7/site-packages/dynamic_validator/__init__.py", line 1, in <module>  
> from .field_validation import ModelFieldRequiredMixin  
> ModuleNotFoundError: No module named 'dynamic_validator.field_validation'
> 

Steps to reproduce: 

1. install via pipenv  
2. add to installed apps `dynamic_validator`   
3. start django server

**Comment by jackton1** [comment]
@upMKuhn Should be resolved all assets are included in the latest version.
``` pip install -U django-dynamic-model-validation```

**Comment by upMKuhn** [comment]
thx
